/***************************************************************
 *
 * Copyright (C) 2026, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// GenCondorObjectParams generates condor/object_params_gen.go, which enumerates
// every object-typed parameter in parameters.yaml and forces the HTCondor
// configuration layer to make a deliberate decision about each one.
//
// Object-typed parameters are lists of structures (Origin.Exports and friends).
// HTCondor's configuration language has a flat string namespace, so each one
// needs an explicit translation into a per-item knob family -- there is no
// generic rule that can be applied to a shape the translator has never seen.
//
// The failure mode this exists to prevent is silence: a developer adds an
// object-typed parameter, nothing anywhere objects, and an HTCondor-mode
// deployment quietly ignores that section of its configuration. To make that
// impossible, the generated constructor takes one argument per object-typed
// parameter, so introducing a new one breaks the build at the call site until a
// handler -- or an explicit declaration that it is unsupported -- is supplied.
func GenCondorObjectParams() {
	names := objectParamNames()

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by go generate; DO NOT EDIT.
//
// Generated from docs/parameters.yaml. Regenerate with "make generate".

//go:build !windows

package condor

// ObjectParamNames lists every object-typed parameter in parameters.yaml, in
// sorted order. It exists so tests can assert that the handler registry covers
// exactly this set.
var ObjectParamNames = []string{
`)
	for _, n := range names {
		fmt.Fprintf(&buf, "\t%q,\n", n)
	}
	buf.WriteString(`}

// ObjectParamSet is a complete set of handlers, one for every object-typed
// parameter. Build it with NewObjectParamSet.
type ObjectParamSet struct {
	handlers map[string]ObjectParamHandler
}

// Handler returns the handler for a parameter, and whether one is registered.
func (s ObjectParamSet) Handler(param string) (ObjectParamHandler, bool) {
	h, ok := s.handlers[param]
	return h, ok
}

// NewObjectParamSet takes one handler per object-typed parameter.
//
// The argument list is generated from parameters.yaml, so adding an
// object-typed parameter there adds an argument here and every call site stops
// compiling until it is given a handler. That is the point: an object-typed
// parameter that HTCondor mode does not know how to translate must be an
// explicit decision (see Unsupported), never an omission.
//
// It panics if a handler is passed for the wrong parameter, which catches an
// argument-order mistake the compiler cannot -- every argument has the same
// type, so only the declared name distinguishes them.
func NewObjectParamSet(
`)
	for _, n := range names {
		fmt.Fprintf(&buf, "\t%s ObjectParamHandler, // %s\n", argName(n), n)
	}
	buf.WriteString(`) ObjectParamSet {
	set := ObjectParamSet{handlers: make(map[string]ObjectParamHandler, len(ObjectParamNames))}
	for i, h := range []ObjectParamHandler{
`)
	for _, n := range names {
		fmt.Fprintf(&buf, "\t\t%s,\n", argName(n))
	}
	buf.WriteString(`	} {
		want := ObjectParamNames[i]
		if h.Param != want {
			panic("condor: handler for " + want + " declares parameter " + h.Param +
				"; the arguments to NewObjectParamSet are out of order")
		}
		set.handlers[want] = h
	}
	return set
}
`)

	outPath, err := filepath.Abs("../condor/object_params_gen.go")
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		panic(fmt.Errorf("failed to write %s: %w", outPath, err))
	}
}

// objectParamNames returns the sorted names of every parameter declared with
// "type: object" in parameters.yaml.
func objectParamNames() []string {
	filename, err := filepath.Abs("../docs/parameters.yaml")
	if err != nil {
		panic(err)
	}
	yamlFile, err := os.Open(filename)
	if err != nil {
		panic(err)
	}
	defer yamlFile.Close()

	names := []string{}
	decoder := yaml.NewDecoder(yamlFile)
	for {
		var entry map[string]any
		if err := decoder.Decode(&entry); err != nil {
			if err == io.EOF {
				break
			}
			panic(fmt.Errorf("document decode failed: %w", err))
		}
		if t, _ := entry["type"].(string); t != "object" {
			continue
		}
		name, ok := entry["name"].(string)
		if !ok {
			panic("object-typed parameter entry is missing its name")
		}
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// argName turns a parameter name into a lowerCamelCase Go argument name, e.g.
// "Origin.Exports" becomes "originExports".
func argName(param string) string {
	var b strings.Builder
	for i, part := range strings.Split(param, ".") {
		if part == "" {
			continue
		}
		if i == 0 {
			b.WriteString(strings.ToLower(part[:1]) + part[1:])
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}
