// Code generated by go generate; DO NOT EDIT.
//
// Generated from docs/parameters.yaml. Regenerate with "make generate".

//go:build !windows

package condor

// ObjectParamNames lists every object-typed parameter in parameters.yaml, in
// sorted order. It exists so tests can assert that the handler registry covers
// exactly this set.
var ObjectParamNames = []string{
	"GeoIPOverrides",
	"Issuer.AuthorizationTemplates",
	"Issuer.OIDCAuthenticationRequirements",
	"LocalCache.StorageDirs",
	"Lotman.PolicyDefinitions",
	"Origin.Exports",
	"Registry.CustomRegistrationFields",
	"Registry.Institutions",
	"Shoveler.IPMapping",
}

// ObjectParamSet is a complete set of handlers, one for every object-typed
// parameter. Build it with NewObjectParamSet.
type ObjectParamSet struct {
	handlers map[string]ObjectParamHandler
}

// Handler returns the handler for a parameter, and whether one is registered.
func (s ObjectParamSet) Handler(param string) (ObjectParamHandler, bool) {
	h, ok := s.handlers[param]
	return h, ok
}

// NewObjectParamSet takes one handler per object-typed parameter.
//
// The argument list is generated from parameters.yaml, so adding an
// object-typed parameter there adds an argument here and every call site stops
// compiling until it is given a handler. That is the point: an object-typed
// parameter that HTCondor mode does not know how to translate must be an
// explicit decision (see Unsupported), never an omission.
//
// It panics if a handler is passed for the wrong parameter, which catches an
// argument-order mistake the compiler cannot -- every argument has the same
// type, so only the declared name distinguishes them.
func NewObjectParamSet(
	geoIPOverrides ObjectParamHandler, // GeoIPOverrides
	issuerAuthorizationTemplates ObjectParamHandler, // Issuer.AuthorizationTemplates
	issuerOIDCAuthenticationRequirements ObjectParamHandler, // Issuer.OIDCAuthenticationRequirements
	localCacheStorageDirs ObjectParamHandler, // LocalCache.StorageDirs
	lotmanPolicyDefinitions ObjectParamHandler, // Lotman.PolicyDefinitions
	originExports ObjectParamHandler, // Origin.Exports
	registryCustomRegistrationFields ObjectParamHandler, // Registry.CustomRegistrationFields
	registryInstitutions ObjectParamHandler, // Registry.Institutions
	shovelerIPMapping ObjectParamHandler, // Shoveler.IPMapping
) ObjectParamSet {
	set := ObjectParamSet{handlers: make(map[string]ObjectParamHandler, len(ObjectParamNames))}
	for i, h := range []ObjectParamHandler{
		geoIPOverrides,
		issuerAuthorizationTemplates,
		issuerOIDCAuthenticationRequirements,
		localCacheStorageDirs,
		lotmanPolicyDefinitions,
		originExports,
		registryCustomRegistrationFields,
		registryInstitutions,
		shovelerIPMapping,
	} {
		want := ObjectParamNames[i]
		if h.Param != want {
			panic("condor: handler for " + want + " declares parameter " + h.Param +
				"; the arguments to NewObjectParamSet are out of order")
		}
		set.handlers[want] = h
	}
	return set
}
